// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mtaA8-ukehKD_W07uUu6J-cbykgLW6c',
    appId: '1:1056178875352:web:81f116508f55354bdd60ad',
    messagingSenderId: '1056178875352',
    projectId: 'flutty-a38f1',
    authDomain: 'flutty-a38f1.firebaseapp.com',
    storageBucket: 'flutty-a38f1.appspot.com',
    measurementId: 'G-X2JXLR4T6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdJamJACbxRKQH9Ba18YsGxF_cQxLzLZQ',
    appId: '1:1056178875352:android:92db7df15ed67b9ddd60ad',
    messagingSenderId: '1056178875352',
    projectId: 'flutty-a38f1',
    storageBucket: 'flutty-a38f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd86PfR7IDFqIJFBdbJQnH4wyKLcH1A0A',
    appId: '1:1056178875352:ios:93231a97f0be06aedd60ad',
    messagingSenderId: '1056178875352',
    projectId: 'flutty-a38f1',
    storageBucket: 'flutty-a38f1.appspot.com',
    iosClientId: '1056178875352-6bp49o131e9jiu5jmlp5eh479e4n2qho.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd86PfR7IDFqIJFBdbJQnH4wyKLcH1A0A',
    appId: '1:1056178875352:ios:2bc104500a16d09fdd60ad',
    messagingSenderId: '1056178875352',
    projectId: 'flutty-a38f1',
    storageBucket: 'flutty-a38f1.appspot.com',
    iosClientId: '1056178875352-kl94jf5ant83e8a0kq5ld603lp4fh0db.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
