// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhUaYtLrAtrlgmzkjcZLMVQ8ceKfK0TK4',
    appId: '1:59872433856:web:42002c65cc956fb1753f25',
    messagingSenderId: '59872433856',
    projectId: 'flotty-bd38d',
    authDomain: 'flotty-bd38d.firebaseapp.com',
    storageBucket: 'flotty-bd38d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZSUS5g2Bo-kMFhtTYFgCh8XpJ9jE8B1w',
    appId: '1:59872433856:android:8517e7375a34fcd3753f25',
    messagingSenderId: '59872433856',
    projectId: 'flotty-bd38d',
    storageBucket: 'flotty-bd38d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvKgGkfCOIUc9w8DHj9X-H_itTGU4R12I',
    appId: '1:59872433856:ios:58d1be82ede8e9b0753f25',
    messagingSenderId: '59872433856',
    projectId: 'flotty-bd38d',
    storageBucket: 'flotty-bd38d.appspot.com',
    iosClientId: '59872433856-823fsktqki5utktq9p3c9ombfkhm96rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvKgGkfCOIUc9w8DHj9X-H_itTGU4R12I',
    appId: '1:59872433856:ios:66cba180c453b8cd753f25',
    messagingSenderId: '59872433856',
    projectId: 'flotty-bd38d',
    storageBucket: 'flotty-bd38d.appspot.com',
    iosClientId: '59872433856-noop87crsopb8ur2tlunhg5de3k2jalr.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
